name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint (flake8)
        run: flake8 smart_lighting_ai_dali tests
      - name: Type check (mypy)
        run: mypy smart_lighting_ai_dali
      - name: Test
        run: pytest
